accounts/urls.py
from django.conf.urls import url
from django.urls import path

from accounts.views import (
    get_user_profile, edit_profile, EditUserProfileView, logout, login
)


urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    url(r'(?P<username>[a-zA-Z0-9]+)$', get_user_profile, name='get_user_profile'),
    url(r'^edit/$', edit_profile, name='edit_profile'),
    url(r'^(?P<username>[a-zA-Z0-9]+)/update/$', EditUserProfileView.as_view(), name='update_profile'),
]

gifcol_app/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url

from .views import abstract_page, new_mediafile, logout, TagLink, bookmark_post, edit_mediafile, moderate_unpub,\
    search_posts
from accounts.views import signup

urlpatterns = [
    path('', abstract_page, name='memepage'),
    url('(?P<filetype>(gif|img|vid))', abstract_page, name='filetypepage'),
    path(r'user/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('new/', new_mediafile, name='new_mediafile'),
    path('moderate/', moderate_unpub, name='moderate_unpub'),
    path('file/<int:pk>/edit', edit_mediafile, name='edit_mediafile'),
    url(r'^signup/$', signup, name='signup'),
    url(r'(?P<id>\d+)/bookmark/$', bookmark_post, name='bookmark_post'),
    path('logout/', logout, name='logout'),
    url(r'^tag/(?P<tag_link>[a-zA-Z0-9]+)$', TagLink.as_view(), name='tag_link'),
    path('search/', search_posts, name='search_results'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gifcol_proj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gifcol_app.urls'))
]

gifcol_app/models.py
from django.db import models
from django.conf import settings
from django.core.exceptions import ValidationError
from gifcol_proj.base_models import TimeStamped, PublishedModel


class Tag(TimeStamped, PublishedModel):
    title = models.CharField(
        verbose_name='Название',
        max_length=32,
        unique=True,
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Тег'
        verbose_name_plural = 'Теги'


def validate_file_extension(value):
    import os
    ext = os.path.splitext(value.name)[1]
    valid_extensions = ['.jpg', '.jpeg', '.png', '.bmp', '.mov', '.mp4', '.avi']
    if ext not in valid_extensions:
        raise ValidationError('File not supported!')
    limit = 5 * 1024 * 1024  # 5 Mb
    if value.size > limit:
        raise ValidationError('File too large. Size should not exceed 5 MiB.')


class Meme(TimeStamped, PublishedModel):
    filetypes = (
        ('gif', 'Гифка'),
        ('video', 'Видео'),
        # ('link', 'Ссылка на видео'),
        ('img', 'Картинка'),
    )

    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        default=0,
    )
    title = models.CharField(
        verbose_name='Название',
        max_length=100,
    )
    description = models.TextField(
        verbose_name='Описание',
        max_length=200
    )
    file = models.FileField(
        upload_to='file/',
        verbose_name='Файл',
        validators=[validate_file_extension]
    )
    filetype = models.CharField(
        max_length=254,
        default='img',
        verbose_name='Тип записи',
        choices=filetypes
    )
    medialink = models.CharField(
        max_length=254,
        verbose_name='Ссылка на видео',
        null=True,
        blank=True,
    )
    tags = models.ManyToManyField(
        Tag,
        verbose_name='Теги',
        related_name='memes',
        blank=True,
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Загруженную запись'
        verbose_name_plural = 'Загруженные записи'

gifcol_app/forms.py
from django import forms
from .models import Meme


class MediaAddForm(forms.ModelForm):
    class Meta:
        model = Meme
        fields = (
            'title',
            'description',
            'file',
            'filetype',
            'medialink',
            'published',
        )
class MediaEditForm(forms.ModelForm):
    class Meta:
        model = Meme
        fields = (
            'title',
            'description',
            'medialink',
            'published',
        )

gifcol_app/views.py
from itertools import count
from django.db.models import Count
from django.db.models import Case, When, Value, BooleanField
from django.views import View
from django.http import HttpResponse, JsonResponse
from django.utils import timezone
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST

from accounts.models import Account
from .forms import MediaAddForm, MediaEditForm
from django.contrib.auth import logout as built_in_logout, get_user_model
from .models import Meme, Tag


# Logout form DeAuth
def logout(request):
    built_in_logout(request)
    return redirect('/')


def abstract_page(request, filetype=None):
    bookmarks = request.user.bookmarks.values_list('id', flat=True) if request.user.is_authenticated else [0]
    memes = Meme.objects.published().filter(
                filetype=filetype or 'video',
    ).order_by(
        'created_at'
    )[:10].annotate(
        bookmarked=Case(
            When(
                id__in=bookmarks,
                then=Value(True),
            ),
            default=Value(False),
            output_field=BooleanField(),
        )
    )
    tags = Tag.objects.published().filter()
    users = Account.objects.all().annotate(post_count=Count('meme'))
    userscount = Account.objects.count()

    
    
    return render(
        request,
        'gifcol_app/memes_base.html',
        {
            'memes': memes,
            'tags': tags,
            'users': users,
            'userscount': userscount,
            

        }
    )


# Загрузить новый файл
def new_mediafile(request):
    if request.method == "POST":
        form = MediaAddForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.created_at = timezone.now()
            post.save()
        return redirect('/')
    else:
        form = MediaAddForm()
    return render(request, 'gifcol_app/edit.html', {'form': form})


def edit_mediafile(request, pk):
    post = get_object_or_404(Meme, pk=pk)
    if request.method == "POST":
        form = MediaEditForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.created_at = timezone.now()
            post.save()
        return redirect('/')
    else:
        form = MediaEditForm(instance=post)
    return render(request, 'gifcol_app/edit_mediafile.html', {'form': form})


def bookmark_post(request, id):
    if request.user.bookmarks.filter(id=id):
        request.user.bookmarks.remove(id)
        return HttpResponse(status=204)
    else:
        request.user.bookmarks.add(id)
        return HttpResponse(status=204)


class TagLink(View):

    def get(self, request, tag_link):
        tag_objects = Meme.objects.filter(tags__title=tag_link)
        return render(
            request,
            'gifcol_app/tag.html',
            {
                'tag_objects': tag_objects,
                'tag_link': tag_link
            }
        )


def moderate_unpub(request):
    memes = Meme.objects.filter(published=False,
                                ).order_by(
        '-created_at'
    )

    return render(
        request,
        'gifcol_app/memes_base.html',
        {
            'memes': memes,
        }
    )


def search_posts(request):
    bookmarks = request.user.bookmarks.values_list('id', flat=True) if request.user.is_authenticated else [0]
    query = request.GET.get('q')
    memes = Meme.objects.published().filter(Q(title__icontains=query) | Q(tags__title=query)).order_by(
        'created_at'
    ).annotate(
        bookmarked=Case(
            When(
                id__in=bookmarks,
                then=Value(True),
            ),
            default=Value(False),
            output_field=BooleanField(),
        )
    ).distinct()

    return render(
        request,
        'gifcol_app/search_results.html',
        {
            'memes': memes,
            'query': query,
        }
    )

gifcol_app/templates/gifcol_app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <link rel="stylesheet" href="{% static 'css/main.css' %}" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.0/css/bootstrap.min.css">
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.2/js/all.js"></script>
        <link rel="stylesheet" href="{% static 'css/lightbox.min.css' %}" />
        <link rel="stylesheet" href="{% static 'css/animated-masonry-gallery.css' %}" />
        <script type="text/javascript" src="{% static 'js/jquery-2.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/animated-masonry-gallery.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/lightbox.min.js' %}"></script>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {% block title %}

        {% endblock %}
    </head>

    <body>
        <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #191919;"> <!-- background-color: #e3f2fd; -->
            <a class="navbar-brand" style="color: #b0b0b0;" href="/">FunGif</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav mr-auto" style="margin:auto">
                    <li class="nav-item" style="display: flex;align-items: center;"> <a class="navtop-link" href="/">Видео</a> </li>
                    <li class="nav-item" style="display: flex;align-items: center;"> <a class="navtop-link" href="/gif">Гифки</a> </li>
                    <li class="nav-item" style="display: flex;align-items: center;"> <a class="navtop-link" href="/img">Картинки</a> </li>
                    <li class="nav-item"> <a class="navtop-link" href="/signup"><button type="button" class="btn btn-primary">Регистрация</button></a> </li>
                </ul>
                <span class="navbar-text">
                    {% if request.user.is_superuser %}
                    <div class="btn-group" role="group">

                            <div class="btn-group" role="group">
                                <button id="btnGroupDrop0" type="button" class="btn btn-warning dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Админка
                                </button>
                              <div class="dropdown-menu" style="min-width: 8rem;" aria-labelledby="btnGroupDrop1">
                                  <a class="dropdown-item" href="/moderate"><button type="button" class="btn btn-warning">Moderate</button></a>
                                  <a class="dropdown-item" href="/admin"><button type="button" class="btn btn-danger">Django Admin</button></a>
                                  <a class="dropdown-item" href="/admin/accounts/account/"><button type="button" class="btn btn-danger">Профили</button></a>
                                  <a class="dropdown-item" href="/admin/gifcol_app/meme/"><button type="button" class="btn btn-danger">Записи</button></a>
                                  <a class="dropdown-item" href="/admin/gifcol_app/tag/"><button type="button" class="btn btn-danger">Теги</button></a>
                              </div>
                            </div>

                    </div>
                    {%endif%}
                    {% if request.user.is_authenticated %}
                            <a style="color:white;" href="/new"><button type="button" class="btn btn-success">Загрузить файл</button></a>
                        <div class="btn-group" role="group">
                            <button id="btnGroupDrop1" type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                {%if user.avatar%}
                                    <img width="30" height="30" src="{{user.avatar.url}}">
                                {%endif%}
                                {{request.user.get_short_name}} [{{request.user.username}}]
                            </button>
                            <div class="dropdown-menu" style="min-width: 8rem;" aria-labelledby="btnGroupDrop1">
                                <a class="dropdown-item" href="{% url 'accounts:get_user_profile' username=request.user %}">Профиль</a>
                                <a class="dropdown-item" href="/user/edit/">Изм. профиль</a>
                                <a class="dropdown-item" href="{% url 'accounts:update_profile' username=request.user %}">Настройки</a>
                                <a class="dropdown-item" href="/logout">Выйти</a>
                            </div>
                        </div>
                    </div>
                    {% else %}
                    <div class="btn-group" role="group">
                        <form class="form-inline" id="login" method="post" action="{% url 'accounts:login' %}">
                            {% csrf_token %}
                            <input class="form-control mb-2 mr-sm-2" type="text" name="username"  placeholder="Введите логин">
                            <input class="form-control mb-2 mr-sm-2" type="password" name="password" placeholder="Введите пароль">
                            <button class="btn btn-secondary mb-2" type="submit">Войти</button>
                        </form>
                    </div>
                    {%endif%}
                </span>
            </div>
        </nav>
        {% block content %}
        {% endblock %}
    </body>
</html>

gifcol_app/templates/gifcol_app/edit.html
{% extends 'gifcol_app/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    {% if user.is_authenticated %}
        <title>Загрузить файл | Meme Archive</title>
        <body style="background-image: url(https://source.unsplash.com/1600x900/?lego);background-size:cover;">
        <form method="post" enctype="multipart/form-data" style="padding-left:15px;">
            {% csrf_token %}
            <br>
            <div class="form-box-new row">
                <div class="col">
                    {{ form.filetype|as_crispy_field }}
                </div>
                <div class="w-100" style="padding-bottom:0.5em;"></div>
                <div class="col">
                    {{ form.title|as_crispy_field }}
                </div>
                <div class="w-100" style="padding-bottom:0.5em;"></div>
                <div class="col">
                    {{ form.description|as_crispy_field }}
                </div>
                <div class="w-100"></div>
                <div class="col">
                    <p class="control-label" id="textCounter" style="font:15px Arial;">Не более 200 символов</p>
                </div>
                <div class="w-100"></div>
                <div class="col" id="id_media_img">
                    {{ form.file|as_crispy_field }}
                </div>
                <div class="w-100"></div>
                <div class="col">
                <u><p class="p-new-file" title="Максимальный размер файла: 5 Мб.
Разрешенные типы файлов: .jpg, .jpeg, .png, .bmp, .mov, .mp4, .avi">Ограничения на загрузку файлов</p></u>
                </div>
                <div class="w-100"></div>
                <div class="col" id="id_media_gif">

                </div>
                <div class="w-100"></div>
                <div class="col" id="id_media_video">

                </div>
                <div class="w-100"></div>
                <div class="col" id="id_media_link">
                    {{ form.medialink|as_crispy_field }}
                </div>
                {% if request.user.is_superuser %}
                    <div class="col-md-12">
                            {{ form.published|as_crispy_field }}
                    </div>
                            {% endif %}
                <div class="w-100" style="padding-bottom:2%;"></div>
                <div class="col">
                    <button id="submitbtn" type="submit" class="btn btn-primary">Загрузить файл</button>
                </div>
            </div>
        </form>
        <script>
$("form").submit(function() {
  if (window.File && window.FileReader && window.FileList && window.Blob) {
    var file = $('#id_file')[0].files[0];

    if (file && file.size > 5 * 1024 * 1024) {
      alert("Загружаемые файл " + file.name + " of type " + file.type + " превышает допустимый размер 5 Мб");
      return false;
    }
  }
});
            //text limit for text area
            $(document).ready(function() {
                $('#id_desc').on('input propertychange', function() {
                    CharLimit(this, 200);
                });
            });

            function CharLimit(input, maxChar) {
                var len = $(input).val().length;
                $('#textCounter').text(maxChar - len + ' символов осталось');
                if(len > maxChar) {
                    $(input).val($(input).val().substring(0, maxChar));
                    $('#textCounter').text(0 + ' символов осталось');
                }
            }
            //text limit for text area
            //Так как select по умолчанию = gif, то скрываем другие поля
            $(document).ready(function() {
                $('#id_media_img_temp').hide();
                $('#id_media_video').hide();
                $('#id_media_link').hide();
            });

            //показываем и скрываем поля динамически в зависимости от значения в поле Select
            $("#id_filetype").change(function() {
                if($(this).val() == "gif") {
                    $('#id_media_gif').show();
                } else {
                    $('#id_media_gif').hide();
                    $('#id_media_img_temp').hide();
                    $('#id_media_video').hide();
                    $('#id_media_link').hide();
                }
                if($(this).val() == "img") {
                    $('#id_media_img_temp').show();
                } else {
                    $('#id_media_img_temp').hide();
                }
                if($(this).val() == "video") {
                    $('#id_media_video').show();
                } else {
                    $('#id_media_video').hide();
                }
                if($(this).val() == "link") {
                    $('#id_media_link').show();
                } else {
                    $('#id_media_link').hide();
                }
            });
        </script>
    {%endif%}
{% endblock %}

gifcol_app/templates/gifcol_app/edit_mediafile.html
{% extends 'gifcol_app/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    {% if user.is_authenticated %}
        <title>Загрузить файл | Meme Archive</title>
        <body style="background-image: url(https://source.unsplash.com/1600x900/?lego);background-size:cover;">
        <form method="post" enctype="multipart/form-data" style="padding-left:15px;">
            {% csrf_token %}
            <br>
            <div class="form-box row">
            <div class="row">
                    <div class="col-md-7">
                        <div class="row">
                            <div class="col-md-12">
                                {{ form.title|as_crispy_field }}
                            </div>
                            <div class="col-md-12">
                                {{ form.description|as_crispy_field }}
                            </div>
                            <div class="col-md-12">
                                <p class="control-label" id="textCounter" style="font:15px Arial;">Не более 200 символов</p>
                            </div>
                            {% if request.user.is_superuser %}
                            <div class="col-md-12">
                            {{ form.published|as_crispy_field }}
                            </div>
                            {% endif %}
                            <div class="col-md-12">
                                <button id="submitbtn" type="submit" class="btn btn-primary">Сохранить изменения</button>
                            </div>
                        </div>
                    </div>
                <div class="col-md-5">Превью записи:<br><img style="border-radius:10px;" width="90%" src="{{ form.instance.file.url }}"></div>
            </div>
        </div>
        </form>
    {%endif%}
{% endblock %}

gifcol_app/templates/gifcol_app/imgs.html
{% extends 'gifcol_app/base.html' %}
{% block content %}
<title>Картинки | Meme Archive</title>
    <div class="masonrygal bordered">
        {% for meme in imgposts %}
            <div class="brick">
                <div class="hvrbox">
                    <img src="{{meme.file.url}}">
                    <div class="hvrbox-layer_top">
                        <div style="float:right;" id="myBtn{{ forloop.counter }}" class="hvrbox-zoom">
                            <i style="font-size:24pt;" class="fas fa-search"></i>
                        </div>
                        <div class="hvrbox-fav">
                            <i class="fas fa-star"></i>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

    {% for meme in imgposts %}
        <!-- The Modal -->
        <div id="myModal{{ forloop.counter }}" class="modal">
            <!-- Modal content -->
            <div class="modal-content" style="width:900px;">
                <span style="padding-bottom:15px;" class="close-btn{{ forloop.counter }}" id="close-span">
                  <button>Вернуться</button>
                </span>
                <div class="row" align="left">
                    <div class="col-sm-8">
                        <img width="100%" height="100%" src="{{ meme.file.url }}">
                    </div>
                    <div class="col-sm-4">
                        {% if is_bookmarked %}
                        dsds
                        {% else %}
                        <a href="{% url 'bookmark_post' id=meme.id%}">
                            Добавить в избранное <i class="fas fa-star"></i>
                        </a>
                        {% endif %}
                        <br>
                        <a title="Редактировать ТТ" class="btn btn-default" href="{% url 'edit_mediafile' pk=meme.pk %}"><b>Изменить запись</b></a>
                        {%if Meme.title%}
                            <br>
                            Название: {{ meme.title }}
                        {%endif%}
                        {%if meme.description %}
                            <br>
                            Описание: {{ meme.description }}

                        {%endif%}
                        <br>
                        Загрузил:
                        {%if user.avatar%}
                            <img width="20" height="20" src="{{user.avatar.url}}">
                        {%endif%}
                        <a href="/user/{{meme.author}}">{{meme.author}}</a>
                        <br>
                        Дата загрузки: {{meme.created_at}}
                        <br>
                            {%if meme.tags %}
                                Теги:
                                {% for tag in meme.tags.published %}
                                        <a href="{% url 'tag_link' tag_link=tag.title %}" class="badge badge-success" style="padding:5px;margin:3px;">
                                            {{ tag }}
                                        </a>
                                {% endfor %}
                            {%endif%}
                        <br>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
    <!-- Цикл для передачи номера объекта в цикле в номер кнопки для PopUp окна -->
{% for meme in imgposts %}
    <script>

            // Get the modal
            var modal{{ forloop.counter }} = document.getElementById("myModal{{ forloop.counter }}");

            // Get the button that opens the modal
            var btn = document.getElementById("myBtn{{ forloop.counter }}");

            // Get the <span> element that closes the modal
            var span = document.getElementsByClassName("close-btn{{ forloop.counter }}")[0];

            // When the user clicks on the button, open the modal
            btn.onclick = function() {
                modal{{ forloop.counter }}.style.display = "block";
            }

            // When the user clicks on <span> (x), close the modal
            span.onclick = function() {
                modal{{ forloop.counter }}.style.display = "none";
            }

            // When the user clicks anywhere outside of the modal, close it
            window.onclick = function(event) {
                if (event.target == modal{{ forloop.counter }}) {
                    modal{{ forloop.counter }}.style.display = "none";
                }
            }

    </script>
{% endfor %}
{% endblock %}

gifcol_app/templates/gifcol_app/masonry-images-example.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/lightbox.min.css' %}"/>
<link rel="stylesheet" href="{% static 'css/animated-masonry-gallery.css' %}"/>
<script type="text/javascript" src="{% static 'js/jquery-2.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
<script type="text/javascript" src="{% static 'js/animated-masonry-gallery.js' %}"></script>


<div id="gallery-content">
    <div id="gallery-content-center" style="position: relative; overflow: hidden; height: 1200px;" class="gallery-content-center-full isotope">
        <a class="example-image-link" href="_assets/1.jpg" data-lightbox="example-set" data-title="pic1"><img class="example-image" src="_assets/1.jpg" class="all landscape isotope-item" style="position: absolute; left: 0px; top: 0px; transform: translate3d(620px, 420px, 0px) scale3d(1, 1, 1); opacity: 1;" alt=""/></a>
        <a class="example-image-link" href="_assets/2.jpg" data-lightbox="example-set" data-title="pic1"><img class="example-image" src="_assets/2.jpg" class="all landscape isotope-item" style="position: absolute; left: 0px; top: 0px; transform: translate3d(0px, 422px, 0px) scale3d(1, 1, 1); opacity: 1;" alt=""/></a>
        <a class="example-image-link" href="_assets/3.jpg" data-lightbox="example-set" data-title="pic1"><img class="example-image" src="_assets/3.jpg" class="all landscape isotope-item" style="position: absolute; left: 0px; top: 0px; transform: translate3d(310px, 422px, 0px) scale3d(1, 1, 1); opacity: 1;" alt=""/></a>
        <a class="example-image-link" href="_assets/4.jpg" data-lightbox="example-set" data-title="pic1"><img class="example-image" src="_assets/4.jpg" class="all landscape isotope-item" style="position: absolute; left: 0px; top: 0px; transform: translate3d(620px, 420px, 0px) scale3d(1, 1, 1); opacity: 1;" alt=""/></a>
        <a class="example-image-link" href="_assets/5.jpg" data-lightbox="example-set" data-title="pic1"><img class="example-image" src="_assets/5.jpg" class="all landscape isotope-item" style="position: absolute; left: 0px; top: 0px; transform: translate3d(0px, 422px, 0px) scale3d(1, 1, 1); opacity: 1;" alt=""/></a>
        <a class="example-image-link" href="_assets/6.jpg" data-lightbox="example-set" data-title="pic1"><img class="example-image" src="_assets/6.jpg" class="all landscape isotope-item" style="position: absolute; left: 0px; top: 0px; transform: translate3d(310px, 422px, 0px) scale3d(1, 1, 1); opacity: 1;" alt=""/></a>
        <a class="example-image-link" href="_assets/7.jpg" data-lightbox="example-set" data-title="pic1"><img class="example-image" src="_assets/7.jpg" class="all landscape isotope-item" style="position: absolute; left: 0px; top: 0px; transform: translate3d(620px, 420px, 0px) scale3d(1, 1, 1); opacity: 1;" alt=""/></a>
        <a class="example-image-link" href="_assets/8.jpg" data-lightbox="example-set" data-title="pic1"><img class="example-image" src="_assets/8.jpg" class="all landscape isotope-item" style="position: absolute; left: 0px; top: 0px; transform: translate3d(0px, 422px, 0px) scale3d(1, 1, 1); opacity: 1;" alt=""/></a>
        <script src="dist/js/lightbox.min.js"></script>
    </div>
</div>